name: deoldify
channels:
- fastai
- pytorch
- defaults
dependencies:
- pip
- python>=3.7.3
- pytorch=1.11.0
- torchvision
- torchaudio
- tensorboardX=1.6
- yt-dlp
- jupyterlab
- pillow>=9.0.0
- ffmpeg
- pip:
  - ffmpeg-python
  - opencv-python>=3.3.0.10
  - wandb
