name: deoldify
channels:
- fastai
- pytorch
- defaults
- peterjc123
dependencies:
- scipy
- cuda90
- cudnn
- numpy
- pillow
- jpeg
- spacy
- zlib
- freetype
- libtiff
- bleach
- certifi
- cffi
- cycler
- decorator
- entrypoints
- expat
- html5lib
- icu
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- jedi
- jinja2
- jsonschema 
- libiconv
- libpng
- libsodium
- lxml==4.2.1
- libxml2
- markupsafe
- matplotlib
- mistune
- mkl
- nbconvert
- nbformat
- notebook
- numpy
- olefile
- openssl
- pandas
- pandocfilters
- path.py
- patsy
- pcre
- pexpect
- pickleshare
- pillow
- pip
- prompt_toolkit
- pycparser
- pygments
- pyparsing
- pyqt
- python>=3.6.0
- python-dateutil
- pytz
- pyzmq
- qt
- qtconsole
- scipy
- seaborn
- setuptools
- simplegeneric
- sip
- six
- sqlite
- statsmodels
- testpath
- tk
- tornado<5
- tqdm
- traitlets
- wcwidth
- wheel
- widgetsnbextension
- xz
- zeromq
- pytorch==0.4.1
- bcolz
- prompt_toolkit
- pytest
- pip:
  - tensorflow-gpu
  - torchvision>=0.2.0
  - opencv-python
  - isoweek
  - pandas_summary==0.0.5
  - torchtext
  - graphviz
  - sklearn_pandas
  - feather-format
  - plotnine
  - kaggle-cli
  - ipywidgets
  - jupyterlab>=0.34.3
  - tensorboardX
